// BANNER MODALS
export const DEPOSIT_MODAL = 'DEPOSIT_MODAL';
export const FIAT_DEPOSIT_MODAL = 'FIAT_DEPOSIT_MODAL';
export const NFT_DEPOSIT_MODAL = 'NFT_DEPOSIT_MODAL';
export const ADD_CARD_MODAL = 'ADD_CARD_MODAL';
export const DEPOSIT_SUCCESS_MODAL = 'DEPOSIT_SUCCESS_MODAL';

// SUPPORT MODAL
export const CONTACT_SUPPORT_MODAL = 'CONTACT_SUPPORT_MODAL';

// VIEW NFT MODAL
export const VIEW_NFT_MODAL = 'VIEW_NFT_MODAL';

// CRYPTO DEPOSIT MODAL
export const CRYPTO_DEPOSIT_MODAL = 'CRYPTO_DEPOSIT_MODAL';

// Buy Modals
export const BUY_MODAL = 'BUY_MODAL';
export const ADD_NEW_CARD_MODAL = 'ADD_NEW_CARD_MODAL';
export const CONFIRM_BUY_CRYPTO_MODAL = 'CONFIRM_BUY_CRYPTO_MODAL';
export const BUY_SWAP_SUCCESS_MODAL = 'BUY_SWAP_SUCCESS_MODAL';
export const BUY_CRYPTO_LISTING = 'BUY_CRYPTO_LISTING';

//Sell Modals
export const SELL_MODAL = 'SELL_MODAL';
export const CRYPTO_SELL_LISTING_MODAL = 'CRYPTO_SELL_LISTING_MODAL';
export const CONFIRM_SELL_CRYPTO_MODAL = 'CONFIRM_SELL_CRYPTO_MODAL';
export const SELL_SWAP_SUCCESS_MODAL = 'SELL_SWAP_SUCCESS_MODAL';

// SWAP MODALS
export const SWAP_CRYPTO_MODAL = 'SWAP_CRYPTO_MODAL';
export const SWAP_CONFIRMATION_MODAL = 'SWAP_CONFIRMATION_MODAL';
export const SWAP_SUCCESS_MODAL = 'SWAP_SUCCESS_MODAL';

// TRANSFER MODALS
export const TRANSFER_CRYPTO_MODAL = 'TRANSFER_CRYPTO_MODAL';
export const CONFIRM_TRANSFER_CRYPTO_MODAL = 'CONFIRM_TRANSFER_CRYPTO_MODAL';
export const TRANSFER_SWAP_SUCCESS_MODAL = 'TRANSFER_SWAP_SUCCESS_MODAL';

// Transaction Details Modals
export const CRYPTO_TRANSACTION_DETAILS_MODAL =
  'CRYPTO_TRANSACTION_DETAILS_MODAL';
export const WEALTH_TRANSACTION_DETAILS_MODAL =
  'WEALTH_TRANSACTION_DETAILS_MODAL';

// Filter Modal
export const FILTER_MODAL = 'FILTER_MODAL';

// Profile
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHECK_EMAIL = 'CHECK_EMAIL';
export const VERIFICATION_MODAL = 'VERIFICATION_MODAL';
export const VIDEO_MODAL = 'VIDEO_MODAL';
export const LEARNING_MODAL = 'LEARNING_MODAL';

// Card Modal
export const REMOVE_CARD = 'REMOVE_CARD';

// Currency Modal
export const CURRENCY_MODAL = 'CURRENCY_MODAL';

// Disclaimer Modal
export const DISCLAIMER_MODAL = 'DISCLAIMER_MODAL';

export const VIEW_IMAGE_SLIDER_MODAL = 'VIEW_IMAGE_SLIDER_MODAL';

// TOP_UP
export const TOP_UP_BALANCE_MODAL = 'TOP_UP_BALANCE_MODAL';
export const TOP_UP_SUCCESS_MODAL = 'TOP_UP_SUCCESS_MODAL';

// INVESTMENT
export const INVEST_MODAL = 'INVEST_MODAL';
export const INVEST_SUMMARY_MODAL = 'INVEST_SUMMARY_MODAL';
export const INVESTMENT_SUCCESS_MODAL = 'INVESTMENT_SUCCESS_MODAL';

//WITHDRAW
export const WITHDRAW_MODAL = 'WITHDRAW_MODAL';

export const CHART_FILTER_DROPDOWN = 'CHART_FILTER_DROPDOWN';
export const CHART_OPTIONS_DROPDOWN = 'CHART_OPTIONS_DROPDOWN';
export const PROJECT_FILTER_MODAL = 'PROJECT_FILTER_MODAL';

// OFFER MODALS
export const OFFER_ACCEPTANCE_MODAL = 'OFFER_ACCEPTANCE_MODAL';
export const CREATE_OFFER_MODAL = 'CREATE_OFFER_MODAL';
export const OFFER_CREATED_MODAL = 'OFFER_CREATED_MODAL';
export const OFFER_SUCCESS_MODAL = 'OFFER_SUCCESS_MODAL';
export const CANCEL_OFFER_MODAL = 'CANCEL_OFFER_MODAL';

// CHAT MODALS
export const CHAT_CONVERSATIONS_LIST_MODAL = 'CHAT_CONVERSATIONS_LIST_MODAL';
export const CHAT_MODAL = 'CHAT_MODAL';

// MARKET PLACE TABS
export const PRIMARY_MARKET = 'PRIMARY_MARKET';
export const SECONDARY_MARKET = 'SECONDARY_MARKET';
export const WEALTH_ASSETS_FILTER_MODAL = 'WEALTH_ASSETS_FILTER_MODAL';

export const FOOTER_OPTION_MENU = 'FOOTER_OPTION_MENU';
export const FOOTER_MENU_HUB = 'FOOTER_MENU_HUB';

export const ASSETS_LISTING_ACTION_MODAL = 'ASSETS_LISTING_ACTION_MODAL';
export const CHAIN_DROPDOWN_MODAL = 'CHAIN_DROPDOWN_MODAL';
export const MARKET_PLACE_ASSETS_ACTIONS = 'MARKET_PLACE_ASSETS_ACTIONS';
export const ASSET_FILTER_MODAL = 'ASSET_FILTER_MODAL';

// Version Details
export const VERSION_DETAIL_MODAL = 'VERSION_DETAIL_MODAL';

//NeoBanking Action Modal
export const ACTION_BUTTON_MODAL = 'ACTION_BUTTON_MODAL';
export const ACCOUNT_DETAIL_MODAL = 'ACCOUNT_DETAIL_MODAL';
export const RECEIVE_CURRENCY_MODAL = 'RECEIVE_CURRENCY_MODAL';
export const SEND_CURRENCY_MODAL = 'SEND_CURRENCY_MODAL';
export const SUCCESSFULLY_SEND_MODAL = 'SUCCESSFULLY_SEND_MODAL';
export const EXCHANGE_CURRENCY_MODAL = 'EXCHANGE_CURRENCY_MODAL';
export const PREVIEW_EXCHANGE_CURRENCY_MODAL =
  'PREVIEW_EXCHANGE_CURRENCY_MODAL';
export const SUCCESSFULLY_EXCHANGE_CURRENCY_MODAL =
  'SUCCESSFULLY_EXCHANGE_CURRENCY_MODAL';

// Idle warning
export const IDLE_WARNING_MODAL = 'IDLE_WARNING_MODAL';

// Cards Modal
export const CARD_DETAIL_MODAL = 'CARD_DETAIL_MODAL';
export const CARD_DEPOSIT_MODAL = 'CARD_DEPOSIT_MODAL';
export const CARD_WITHDRAW_MODAL = 'CARD_WITHDRAW_MODAL';
export const REVEAL_PIN_MODAL = 'REVEAL_PIN_MODAL';
export const CARD_CONFIRM_WITHDRAW_MODAL = 'CARD_CONFIRM_WITHDRAW_MODAL';
export const CARD_SUCCESS_WITHDRAW_MODAL = 'CARD_SUCCESS_WITHDRAW_MODAL';
export const FREEZE_CARD_MODAL = 'FREEZE_CARD_MODAL';
export const REPORT_MISSING_MODAL = 'REPORT_MISSING_MODAL';
export const LIMIT_FEE_MODAL = 'LIMIT_FEE_MODAL';
export const ACTIVATE_CARD_MODAL = 'ACTIVATE_CARD_MODAL';

export const TRANSACTION_DETAIL_MODAL = 'TRANSACTION_DETAIL_MODAL';
export const CREATE_STRIGA_CARD_MODAL = 'CREATE_STRIGA_CARD_MODAL';
export const CREATE_PHYSICAL_OR_VIRTUAL_CARD_MODAL =
  'CREATE_PHYSICAL_OR_VIRTUAL_CARD_MODAL';
export const CARD_ACTION_MODAL = 'CARD_ACTION_MODAL';
export const ACTIVATE_PHYSICAL_CARD = 'ACTIVATE_PHYSICAL_CARD';
export const ACTIVATE_CARD_SUCCESS_MODAL = 'ACTIVATE_CARD_SUCCESS_MODAL';
export const CREATE_VIRTUAL_OR_PHYSICAL_CARD_MODAL =
  'CREATE_VIRTUAL_OR_PHYSICAL_CARD_MODAL';
export const SET_3DS_PASSWORD_MODAL = 'SET_3DS_PASSWORD_MODAL';
export const CREATE_VIRTUAL_OR_PHYSICAL_CARD_SUCCESS_MODAL =
  'CREATE_VIRTUAL_OR_PHYSICAL_CARD_SUCCESS_MODAL';
export const CREATE_PHYSICAL_CARD_MODAL = 'CREATE_PHYSICAL_CARD_MODAL';
export const SET_3DS_PASSWORD_FOR_PHYSICAL_CARD_MODAL =
  'SET_3DS_PASSWORD_FOR_PHYSICAL_CARD_MODAL';
export const DELIVERY_METHOD_MODAL = 'DELIVERY_METHOD_MODAL';

export const CHANGE_CURRENCY_MODAL = 'CHANGE_CURRENCY_MODAL';

export const CHANGE_CURRENCY_SUCCESS_MODAL = 'CHANGE_CURRENCY_SUCCESS_MODAL';

//  Terminate Card
export const TERMINATE_CARD_MODAL = 'TERMINATE_CARD_MODAL';
export const TERMINATE_CARD_CONFIRMATION_CODE_MODAL =
  'TERMINATE_CARD_CONFIRMATION_CODE_MODAL';
export const SUCCESSFULLY_TERMINATE_CARD_MODAL =
  'SUCCESSFULLY_TERMINATE_CARD_MODAL';

// Card Settings
export const CARD_SETTINGS_MODAL = 'CARD_SETTINGS_MODAL';
export const CARD_TRANSACTION_LIMIT = 'CARD_TRANSACTION_LIMIT';
export const SET_NEW_CARD_3DS_PASSWORD = 'SET_NEW_CARD_3DS_PASSWORD';

// Delievery-details modal
export const DELIVERY_DETAILS_MODAL = 'DELIVERY_DETAILS_MODAL';

// OTP-verification modal
export const CRYPTO_WITHDRAWAL_OTP_VERIFICATION_MODAL =
  'CRYPTO_WITHDRAWAL_OTP_VERIFICATION_MODAL';

// Yield Modals
export const YIELD_CHART_FILTER_MODAL = 'YIELD_CHART_FILTER_MODAL';

// Cookies
export const ID_TOKEN_COOKIE = 'ID_TOKEN_COOKIE';
export const MFA_TOKEN_COOKIE = 'MFA_TOKEN_COOKIE';
export const OPERATION_ID_COOKIE = 'OPERATION_ID_COOKIE';
export const IS_MFA = 'IS_MFA';
export const YIELD_TRANSACTIONS_MODAL = 'YIELD_TRANSACTIONS_MODAL';

// ASSETS DETAILS MODALS
export const ASSETS_DETAILS_MODAL = 'ASSETS_DETAILS_MODAL';
export const YIELD_CRYPTO_DEPOSIT_MODAL = 'YIELD_CRYPTO_DEPOSIT_MODAL';
export const YIELD_CRYPTO_WITHDRAW_MODAL = 'YIELD_CRYPTO_WITHDRAW_MODAL';
export const YIELD_CONFIRM_DEPOSIT_MODAL = 'YIELD_CONFIRM_DEPOSIT_MODAL';
export const YIELD_CONFIRM_WITHDRAW_MODAL = 'YIELD_CONFIRM_WITHDRAW_MODAL';
export const YIELD_CRYPTO_DEPOSIT_SUCCESS_MODAL =
  'YIELD_CRYPTO_DEPOSIT_SUCCESS_MODAL';
export const YIELD_CRYPTO_WITHDRAW_SUCCESS_MODAL =
  'YIELD_CRYPTO_WITHDRAW_SUCCESS_MODAL';
export const YIELD_ASSETS_MODAL = 'YIELD_ASSETS_MODAL';
export const YIELD_FILTER_MODAL = 'YIELD_FILTER_MODAL';

// Staking Modals
export const STAKING_MODAL = 'STAKING_MODAL';
export const STAKING_SUCCESS_MODAL = 'STAKING_SUCCESS_MODAL';
export const STAKING_TRANSACTIONS_MODAL = 'STAKING_TRANSACTIONS_MODAL';
export const STAKING_REWARDS_MODAL = 'STAKING_REWARDS_MODAL';
export const ASSETS_DROPDOWN = 'ASSETS_DROPDOWN';

export const STAKING_ACTION_MODAL = 'STAKING_ACTION_MODAL';

// Unstake Modals
export const UNSTAKE_MODAL = 'UNSTAKE_MODAL';
export const UNSTAKE_WARNING_MODAL = 'UNSTAKE_WARNING_MODAL';
export const UNSTAKE_SUCCESS_MODAL = 'UNSTAKE_SUCCESS_MODAL';

// Striga OTP Modal
export const STRIGA_OTP_MODAL = 'STRIGA_OTP_MODAL';
export const STRIGA_UI_COMPONENT_OTP_MODAL = 'STRIGA_UI_COMPONENT_OTP_MODAL';

// OTP verification types
export const VERIFY_CONSENT = 'VERIFY_CONSENT';
export const VERIFY_TRANSACTION = 'VERIFY_TRANSACTION';

// CARD'S BLOCKED TYPES ARRAY
export const BLOCK_TYPES = ['COUNTERFEIT', 'FRAUDULENT', 'LOST', 'STOLEN'];
